apiVersion: v1
kind: Service
metadata:
  name: {{ include "hivezodiac.fullname" . }}
  labels:
    app: {{ include "hivezodiac.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- range .Values.service.ports }}
    - name: {{ .name }}
      port: {{ .port }}
      targetPort: {{ .targetPort }}
      protocol: {{ default "TCP" .protocol }}
    {{- end }}
  selector:
    app: {{ include "hivezodiac.fullname" . }}
