apiVersion: v1
kind: Service
metadata:
  name: {{ include "hivezodiac.fullname" . }}
  labels:
    app: {{ include "hivezodiac.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.containerPort }}
      protocol: TCP
  selector:
    app: {{ include "hivezodiac.fullname" . }}
