replicaCount: 1

image:
  repository: hivezodiac
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  ports:
    - name: http
      port: 8080
      targetPort: 8080
    - name: mqtt
      port: 1883
      targetPort: 1883

containerPorts:
  - containerPort: 8080
  - containerPort: 1883

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}

imagePullSecrets: []

extraEnv: []

extraVolumes: []
extraVolumeMounts: []
